# /etc/zsh/zprofile: system-wide .zprofile file for zsh(1).
#
# This file is sourced only for login shells (i.e. shells
# invoked with "-" as the first character of argv[0], and
# shells invoked with the -l flag.)
#
# Global Order: zshenv, zprofile, zshrc, zlogin

test -f /etc/profile.d/rvm.sh && source /etc/profile.d/rvm.sh

WORKING_DIRECTORY="/workspaces/nginx-nodejs-redis"

if [ -z "$SHELL_LOGGED_IN" ] && [ ! "$TERM_PROGRAM" = "vscode" ]; then
  cd "$WORKING_DIRECTORY"
  export SHELL_LOGGED_IN=true
fi

if [ ! -z "$SSH_CONNECTION" ]; then
  while read line
  do
      key=$(echo $line | sed "s/=.*//")
      value=$(echo $line | sed "s/$key=//1")
      decodedValue=$(echo $value | base64 -d)
      export $key="$decodedValue"
  done < /workspaces/.codespaces/shared/.env-secrets
fi


